site_name: My Docs
nav:
  - Home: index.md
  - About: about.md
site_url: https://example.com
theme:
  name: material
  features:
    - navigation.footer

  palette: 
    scheme: slate
    primary: indigo
    accent: indigo
copyright: 'Copyright © 2025 CopterLab'